# Numpy Indexing & Selection

In [2]:
import numpy as np

In [26]:
arr = np.arange(0,11)

In [8]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5]=100

In [16]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
#TRICKY THING
print(arr) 
new_arr = arr[0:5] #Only a reference is made with new array to copy explicitly use copy method in numpy
print(new_arr)
new_arr[:] = 100
print(new_arr)
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]
[100 100 100 100 100]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [39]:
new_copy_arr = arr.copy()
new_copy_arr[:]=111
print(new_copy_arr)
print(arr)

[111 111 111 111 111 111 111 111 111 111 111]
[100 100 100 100 100   5   6   7   8   9  10]


# MATRIX

In [12]:
arr = np.random.rand(25)

In [13]:
print(arr)

[0.64412193 0.76856994 0.14671513 0.74822739 0.8625864  0.26749205
 0.30230821 0.48935963 0.80049367 0.83091369 0.5417256  0.51572979
 0.0526272  0.26509082 0.27201857 0.20570146 0.91663815 0.73551524
 0.68634436 0.72314364 0.14919751 0.53670481 0.57420993 0.69578623
 0.85058388]


In [14]:
arr=arr.reshape(5,5)

In [15]:
print(arr)

[[0.64412193 0.76856994 0.14671513 0.74822739 0.8625864 ]
 [0.26749205 0.30230821 0.48935963 0.80049367 0.83091369]
 [0.5417256  0.51572979 0.0526272  0.26509082 0.27201857]
 [0.20570146 0.91663815 0.73551524 0.68634436 0.72314364]
 [0.14919751 0.53670481 0.57420993 0.69578623 0.85058388]]


In [17]:
arr[:,:]
print(arr.shape)

(5, 5)


In [22]:
arr[1:3,1:3]

array([[0.30230821, 0.48935963],
       [0.51572979, 0.0526272 ]])

In [30]:
bool_arr=arr>.56
print(bool_arr,"\n")
print(arr)

[[ True  True False  True  True]
 [False False False  True  True]
 [False False False False False]
 [False  True  True  True  True]
 [False False  True  True  True]] 

[[0.64412193 0.76856994 0.14671513 0.74822739 0.8625864 ]
 [0.26749205 0.30230821 0.48935963 0.80049367 0.83091369]
 [0.5417256  0.51572979 0.0526272  0.26509082 0.27201857]
 [0.20570146 0.91663815 0.73551524 0.68634436 0.72314364]
 [0.14919751 0.53670481 0.57420993 0.69578623 0.85058388]]


In [28]:
print(arr[bool_arr])

[0.64412193 0.76856994 0.74822739 0.8625864  0.80049367 0.83091369
 0.91663815 0.73551524 0.68634436 0.72314364 0.57420993 0.69578623
 0.85058388]


In [11]:
arr_bck = np.arange(1,26)
print(arr_bck)
arr_bck_2d = arr_bck.reshape(5,5)
print("\n","\n",arr_bck_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
ar = arr_bck_2d
print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
ar * ar

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [15]:
ar + ar

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [16]:
ar - ar

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
ar * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [19]:
ar[0,0]=0

In [20]:
print(ar)

[[ 0  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [21]:
ar/ar

C:\ProgramData\Anaconda3\envs\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
ar ** 2

array([[  0,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]], dtype=int32)

In [23]:
np.sqrt(ar)

array([[0.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ]])

In [24]:
np.exp(ar)

array([[1.00000000e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10]])

# https://docs.scipy.org/doc/numpy/reference/ufuncs.html